config/routes.rb
Rails.application.routes.draw do
  resources :applicants do
    patch :change_stage, on: :member
  end
  resources :jobs
  devise_for :users,
  path: '',
  controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  },
  path_names: {
    sign_in: 'login',
    password: 'forgot',
    confirmation: 'confirm',
    sign_up: 'sign_up',
    sign_out: 'signout'
  }

  get 'dashboard/show'
  get 'dashboard/show'

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :job
  has_one_attached :resume

  enum stage: {
    application: 'application',
    interview: 'interview',
    offer: 'offer',
    hired: 'hire'
  }

  enum status: {
    active: 'active',
    inactive: 'inactive'
  }

  validates_presence_of :first_name, :last_name, :email

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_applicant, only: %i[ show edit update destroy change_stage ]

  def change_stage
    @applicant.update(applicant_params)
    head :ok
  end

  # GET /applicants or /applicants.json
  def index
    if search_params.present?
      @applicants = Applicant.includes(:job)
      @applicants = @applicants.where(job_id: search_params[:job]) if search_params[:job].present?
      @applicants = @applicants.where('first_name ILIKE ? OR last_name ILIKE ?', "%#{search_params[:query]}%", "%#{search_params[:query]}%") if search_params[:query].present?
      if search_params[:sort].present?
        sort = search_params[:sort].split('-')
        @applicants = @applicants.order("#{sort[0]} #{sort[1]}")
      end
    else
      @applicants = Applicant.includes(:job).all
    end
  end

  # GET /applicants/1 or /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    html = render_to_string(partial: 'form', locals: { applicant: Applicant.new })
    render operations: cable_car
      .inner_html('#slideover-content', html: html)
      .text_content('#slideover-header', text: 'Add an applicant')
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants or /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)
    if @applicant.save
      html = render_to_string(partial: 'card', locals: { applicant: @applicant })
      render operations: cable_car
        .prepend("#applicants-#{@applicant.stage}", html: html)
        .dispatch_event(name: 'submit:success')
    else
      html = render_to_string(partial: 'form', locals: { applicant: @applicant })
      render operations: cable_car
        .inner_html('#applicant-form', html: html), status: :unprocessable_entity
    end
  end

  # PATCH/PUT /applicants/1 or /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to applicant_url(@applicant), notice: "Applicant was successfully updated." }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1 or /applicants/1.json
  def destroy
    @applicant.destroy

    respond_to do |format|
      format.html { redirect_to applicants_url, notice: "Applicant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def search_params
    params.permit(:query, :job, :sort)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_applicant
    @applicant = Applicant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def applicant_params
    params.require(:applicant).permit(:first_name, :last_name, :email, :phone, :stage, :status, :job_id, :resume)
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_applicant.html.erb
<div id="<%= dom_id applicant %>">
  <p>
    <strong>First name:</strong>
    <%= applicant.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= applicant.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= applicant.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= applicant.phone %>
  </p>

  <p>
    <strong>Stage:</strong>
    <%= applicant.stage %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= applicant.status %>
  </p>

  <p>
    <strong>Job:</strong>
    <%= applicant.job_id %>
  </p>

</div>

app/views/applicants/_card.html.erb
<div class="flex flex-col pb-2 overflow-auto" data-id="<%= applicant.id %>">
  <div class="relative flex flex-col items-start p-4 mt-3 bg-gray-100 rounded-lg cursor-move bg-opacity-90 group hover:bg-opacity-100">
    <h4 class="text-gray-900"><%= link_to applicant.name, applicant, class: "cursor-pointer" %></h4>
    <p class="text-sm text-gray-700"><%= applicant.job.title %> in <%= applicant.job.location %></p>
    <div class="flex items-center w-full mt-3 text-xs font-medium text-gray-400">
      <div class="flex items-center" title="Application Date">
        <%= inline_svg_tag 'calendar.svg', class: 'h-4 w-4 inline-block' %>
        <span class="ml-1 leading-none"><%= l(applicant.created_at.to_date, format: :short) %></span>
      </div>
    </div>
  </div>
</div>

app/views/applicants/_form.html.erb
<%= form_with(model: applicant, id: 'applicant-form', html: { class: "space-y-6" }, data: { remote: true }) do |form| %>
  <% if applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>
      <ul>
        <% applicant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "mt-1" %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "mt-1" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "mt-1" %>
  </div>
  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "mt-1" %>
  </div>
  <div class="form-group">
    <%= form.label :stage %>
    <%= form.select :stage, options_for_select(Applicant.stages.map{ |key, _value| [key.humanize, key]}, applicant.stage), {}, { class: "mt-1" } %>
  </div>
  <div class="form-group">
    <%= form.label :job_id %>
    <%= form.select :job_id, options_for_select(Job.where(account_id: current_user.account_id).order(:title).pluck(:title, :id)), {}, { class: "mt-1" } %>
  </div>
  <div class="form-group">
    <%= form.label :resume %>
    <%= form.file_field :resume, direct_upload: true, accept: "application/pdf" %>
  </div>
  <%= form.submit 'Submit', class: 'btn-primary float-right' %>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Show this applicant", @applicant %> |
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/index.html.erb
<div class="flex items-baseline justify-between mb-6">
  <h2 class="mt-6 text-3xl font-extrabold text-gray-700">
    Applicants
  </h2>
  <%= link_to "Add a new applicant", new_applicant_path, class: "btn-primary-outline", data: { action: "mouseup->slideover#open", remote: true } %>
</div>
<div class="flex mb-6 justify-end">
  <%= form_with url: applicants_path, method: :get, class: "flex items-baseline" do |form| %>
    <div class="form-group mr-2">
      <%= form.label :sort, class: "sr-only" %>
      <%= form.select :sort, options_for_select([['Application Date Ascending', 'created_at-asc'], ['Application Date Descending', 'created_at-desc']], params[:sort]) %>
    </div>
    <div class="form-group mr-2">
      <%= form.label :job, class: "sr-only" %>
      <%= form.select :job, options_for_select(Job.where(account_id: current_user.account_id).order(:title).pluck(:title, :id), params[:job]), { include_blank: 'All Jobs' } %>
    </div>
    <div class="form-group mr-2">
      <%= form.label :query, class: "sr-only" %>
      <%= form.text_field :query, placeholder: "Search applicants", value: params[:query] %>
    </div>
    <%= form.button "Filter", class: "btn-primary" %>
  <% end %>
</div>
<div class="flex items-baseline justify-between">
  <div class="flex flex-grow mt-4 space-x-6 overflow-auto" data-controller="drag" data-drag-url-value="/applicants/:id/change_stage" data-drag-attribute-value="applicant[stage]">
    <% [:application, :interview, :offer, :hired].each do |key| %>
      <div class="flex flex-col flex-shrink-0 w-72">
        <div class="flex items-center flex-shrink-0 h-10 px-2">
          <span class="block text-lg font-semibold"><%= key.to_s.humanize %></span>
        </div>
        <div id="applicants-<%= key %>" data-drag-target="list" data-new-value="<%= key.to_s %>" class="h-full">
          <% @applicants.where(stage: key).each do |applicant| %>
            <%= render "card", applicant: applicant %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @applicant %>

<div>
  <%= link_to "Edit this applicant", edit_applicant_path(@applicant) %> |
  <%= link_to "Back to applicants", applicants_path %>

  <%= button_to "Destroy this applicant", @applicant, method: :delete %>
</div>